// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface CloudflareBindings {
}
